### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by takaya-imai** [btcontract/olympus#1]
I got exception when I boot the olympus server as test.
I have to install OracleJava instead of OpenJava?

```
~/olympus$ java -jar /home/xxx/olympus/target/scala-2.11/olympus-assembly-1.0.jar production "{\"privKey\":\"00000000000000000000000000000000000000000000000000000000000000000000000000000\",\"price\":{\"amount\":0},\"quantity\":0,\"btcApi\":\"http://xxxx:xxxx@127.0.0.1:18332\",\"zmqApi\":\"tcp://127.0.0.1:29000\",\"eclairApi\":\"http://127.0.0.1:8086\",\"eclairSockIp\":\"127.0.0.1\",\"eclairSockPort\":9735,\"eclairNodeId\":\"0251f3d2a57ec9631a555a540bb323d543a760240bc630c8902af7fcb0c624a1aa\",\"rewindRange\":1008,\"ip\":\"xxx.xxx.xxx.xxx\",\"checkByToken\":false, \"eclairPass\":\"xxxxxx\"}"
[main] INFO org.bitcoin.Secp256k1Context - java.lang.UnsatisfiedLinkError: no secp256k1 in java.library.path
[main] INFO org.bitcoin.Secp256k1Context - couldn't find secp256k1 library, defaulting to spongycastle
Exception in thread "main" java.lang.NullPointerException
	at org.bitcoinj.core.ECKey.getPointWithCompression(ECKey.java:232)
	at org.bitcoinj.core.ECKey.fromPrivate(ECKey.java:259)
	at org.bitcoinj.core.ECKey.fromPrivate(ECKey.java:250)
	at com.lightning.olympus.crypto.ECBlindSign.<init>(ECBlind.scala:38)
	at com.lightning.olympus.BlindTokens.<init>(BlindTokens.scala:22)
	at com.lightning.olympus.Responder.<init>(Olympus.scala:63)
	at com.lightning.olympus.Olympus$.server(Olympus.scala:50)
	at org.http4s.server.ServerApp$class.run(ServerApp.scala:79)
	at org.http4s.server.ServerApp$class.main(ServerApp.scala:92)
	at com.lightning.olympus.Olympus$.main(Olympus.scala:27)
	at com.lightning.olympus.Olympus.main(Olympus.scala)
```

**Comment by btcontract** [comment]
Turns out this is an error in my instruction, `privKey` (the one which is used to blind-sign storage tokens can't be all zeros). Here's a correct example: https://github.com/btcontract/olympus/blob/master/src/main/scala/com/lightning/olympus/Olympus.scala#L39-L43

Would look like this in CLI: `java -jar /home/xxx/olympus/target/scala-2.11/olympus-assembly-1.0.jar production "{\"privKey\":\"33337641954423495759821968886025053266790003625264088739786982511471995762588\",\"price\":{\"amount\":0},\"quantity\":0,\"btcApi\":\"http://xxxx:xxxx@127.0.0.1:18332\",\"zmqApi\":\"tcp://127.0.0.1:29000\",\"eclairApi\":\"http://127.0.0.1:8080\",\"eclairSockIp\":\"127.0.0.1\",\"eclairSockPort\":9735,\"eclairNodeId\":\"0251f3d2a57ec9631a555a540bb323d543a760240bc630c8902af7fcb0c624a1aa\",\"rewindRange\":1008,\"ip\":\"xxx.xxx.xxx.xxx\",\"checkByToken\":false, \"eclairPass\":\"xxxxxx\"}"`

**Comment by btcontract** [comment]
Also, it's currently rather slow when rewinding blocks even on testnet so `rewindRange` could be lowered to `7` for example to speed up the startup time.

**Comment by btcontract** [comment]
I've also update Eclair part (conf file needs a password now): https://github.com/btcontract/olympus/commit/ac9f8a035c2d8643ebcca933e97be7ab034e5d1b

**Comment by takaya-imai** [comment]
@btcontract thanks. booted successfully.
